name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger subwork
        uses: actions/github-script@v5
        with:
          script: |
            const workflow = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'subwork.yml',
              ref: context.ref
            });
            console.log(`Workflow ${workflow.data.id} triggered.`);
